.TH  "" "" 
.SH Pandoc with citeproc\-hs
.IP \[bu] 2
[\@nonexistent]
.IP \[bu] 2
\@nonexistent
.IP \[bu] 2
Reference [1] says blah.
.IP \[bu] 2
Reference [1] says blah.
.IP \[bu] 2
Reference [1] says blah.
.IP \[bu] 2
Reference [1] [3] says blah.
.IP \[bu] 2
In a note.[1]
.IP \[bu] 2
A citation group [1],[3].
.IP \[bu] 2
Another one [1].
.IP \[bu] 2
And another one in a note.[2]
.IP \[bu] 2
Citation with a suffix and locator [1].
.IP \[bu] 2
Citation with suffix only [1].
.IP \[bu] 2
Now some modifiers.[3]
.IP \[bu] 2
With some markup [1].
.SH References
.PP
[1] J.
Doe, \f[I]First Book\f[], Cambridge: Cambridge University Press, 2005.
.PP
[2] J.
Doe, “Article,” \f[I]Journal of Generic Studies\f[], vol.
6, 2006, pp.
33\[en]34.
.PP
[3] J.
Doe and J.
Roe, “Why Water Is Wet,” \f[I]Third Book\f[], Smith, S., Ed., Oxford:
Oxford University Press, 2007.
.SH NOTES
.SS [1]
.PP
A citation without locators [3].
.SS [2]
.PP
Some citations [1]\[en][3].
.SS [3]
.PP
Like a citation without author: [1], and now Doe with a locator [2].
