.TH PANDOC 1 "January 8, 2008" "Pandoc User Manuals"
.SH NAME
.PP
pandoc \- general markup converter
.SH SYNOPSIS
.PP
pandoc [\f[I]options\f[]][*input\-file*]...
.SH DESCRIPTION
.PP
Pandoc converts files from one markup format to another.
It can read markdown and (subsets of) reStructuredText, HTML, and LaTeX,
and it can write plain text, markdown, reStructuredText, HTML, LaTeX,
ConTeXt, Texinfo, groff man, MediaWiki markup, RTF, OpenDocument XML,
ODT, DocBook XML, EPUB, and Slidy or S5 HTML slide shows.
.PP
If no \f[I]input\-file\f[] is specified, input is read from
\f[I]stdin\f[].
Otherwise, the \f[I]input\-files\f[] are concatenated (with a blank line
between each) and used as input.
Output goes to \f[I]stdout\f[] by default (though output to
\f[I]stdout\f[] is disabled for the \f[C]odt\f[] and \f[C]epub\f[]
output formats).
For output to a file, use the \f[C]\-o\f[] option:
.IP
.nf
\f[C]
pandoc\ \-o\ output.html\ input.txt
\f[]
.fi
.PP
Instead of a file, an absolute URI may be given.
In this case pandoc will fetch the content using HTTP:
.IP
.nf
\f[C]
pandoc\ \-f\ html\ \-t\ markdown\ http://www.fsf.org
\f[]
.fi
.PP
The input and output formats may be specified using command\-line
options (see \f[B]OPTIONS\f[], below, for details).
If these formats are not specified explicitly, Pandoc will attempt to
determine them from the extensions of the input and output filenames.
If input comes from \f[I]stdin\f[] or from a file with an unknown
extension, the input is assumed to be markdown.
If no output filename is specified using the \f[C]\-o\f[] option, or if
a filename is specified but its extension is unknown, the output will
default to HTML.
Thus, for example,
.IP
.nf
\f[C]
pandoc\ \-o\ chap1.tex\ chap1.txt
\f[]
.fi
.PP
converts \f[I]chap1.txt\f[] from markdown to LaTeX.
And
.IP
.nf
\f[C]
pandoc\ README
\f[]
.fi
.PP
converts \f[I]README\f[] from markdown to HTML.
.PP
Pandoc\[aq]s version of markdown is an extended variant of standard
markdown: the differences are described in the \f[I]README\f[] file in
the user documentation.
If standard markdown syntax is desired, the \f[C]\-\-strict\f[] option
may be used.
.PP
Pandoc uses the UTF\-8 character encoding for both input and output.
If your local character encoding is not UTF\-8, you should pipe input
and output through \f[C]iconv\f[]:
.IP
.nf
\f[C]
iconv\ \-t\ utf\-8\ input.txt\ |\ pandoc\ |\ iconv\ \-f\ utf\-8
\f[]
.fi
.SH OPTIONS
.TP
.B \-f \f[I]FORMAT\f[], \-r \f[I]FORMAT\f[], \-\-from=\f[I]FORMAT\f[],
\-\-read=\f[I]FORMAT\f[]
Specify input format.
\f[I]FORMAT\f[] can be \f[C]native\f[] (native Haskell),
\f[C]markdown\f[] (markdown or plain text), \f[C]rst\f[]
(reStructuredText), \f[C]html\f[] (HTML), or \f[C]latex\f[] (LaTeX).
If \f[C]+lhs\f[] is appended to \f[C]markdown\f[], \f[C]rst\f[], or
\f[C]latex\f[], the input will be treated as literate Haskell source.
.RS
.RE
.TP
.B \-t \f[I]FORMAT\f[], \-w \f[I]FORMAT\f[], \-\-to=\f[I]FORMAT\f[],
\-\-write=\f[I]FORMAT\f[]
Specify output format.
\f[I]FORMAT\f[] can be \f[C]native\f[] (native Haskell), \f[C]plain\f[]
(plain text), \f[C]markdown\f[] (markdown), \f[C]rst\f[]
(reStructuredText), \f[C]html\f[] (HTML), \f[C]latex\f[] (LaTeX),
\f[C]context\f[] (ConTeXt), \f[C]man\f[] (groff man), \f[C]mediawiki\f[]
(MediaWiki markup), \f[C]texinfo\f[] (GNU Texinfo), \f[C]docbook\f[]
(DocBook XML), \f[C]opendocument\f[] (OpenDocument XML), \f[C]odt\f[]
(OpenOffice text document), \f[C]epub\f[] (EPUB book), \f[C]slidy\f[]
(Slidy HTML and javascript slide show), \f[C]s5\f[] (S5 HTML and
javascript slide show), or \f[C]rtf\f[] (rich text format).
Note that \f[C]odt\f[] and \f[C]epub\f[] output will not be directed to
\f[I]stdout\f[]; an output filename must be specified using the
\f[C]\-o/\-\-output\f[] option.
If \f[C]+lhs\f[] is appended to \f[C]markdown\f[], \f[C]rst\f[],
\f[C]latex\f[], or \f[C]html\f[], the output will be rendered as
literate Haskell source.
.RS
.RE
.TP
.B \-s, \-\-standalone
Produce output with an appropriate header and footer (e.g.
a standalone HTML, LaTeX, or RTF file, not a fragment).
.RS
.RE
.TP
.B \-o \f[I]FILE\f[], \-\-output=\f[I]FILE\f[]
Write output to \f[I]FILE\f[] instead of \f[I]stdout\f[].
If \f[I]FILE\f[] is `\f[C]\-\f[]\[aq], output will go to
\f[I]stdout\f[].
.RS
.RE
.TP
.B \-p, \-\-preserve\-tabs
Preserve tabs instead of converting them to spaces.
.RS
.RE
.TP
.B \-\-tab\-stop=\f[I]TABSTOP\f[]
Specify tab stop (default is 4).
.RS
.RE
.TP
.B \-\-strict
Use strict markdown syntax, with no extensions or variants.
.RS
.RE
.TP
.B \-\-reference\-links
Use reference\-style links, rather than inline links, in writing
markdown or reStructuredText.
.RS
.RE
.TP
.B \-R, \-\-parse\-raw
Parse untranslatable HTML codes and LaTeX environments as raw HTML or
LaTeX, instead of ignoring them.
.RS
.RE
.TP
.B \-S, \-\-smart
Use smart quotes, dashes, and ellipses.
(This option is significant only when the input format is
\f[C]markdown\f[].
It is selected automatically when the output format is \f[C]latex\f[] or
\f[C]context\f[].)
.RS
.RE
.TP
.B \-m\f[I]URL\f[], \-\-latexmathml=\f[I]URL\f[]
Use LaTeXMathML to display embedded TeX math in HTML output.
To insert a link to a local copy of the \f[C]LaTeXMathML.js\f[] script,
provide a \f[I]URL\f[].
If no \f[I]URL\f[] is provided, the contents of the script will be
inserted directly into the HTML header.
.RS
.RE
.TP
.B \-\-mathml
Convert TeX math to MathML.
In standalone mode, a small javascript will be inserted that allows the
MathML to be viewed on some browsers.
.RS
.RE
.TP
.B \-\-jsmath=\f[I]URL\f[]
Use jsMath to display embedded TeX math in HTML output.
The \f[I]URL\f[] should point to the jsMath load script; if provided, it
will be linked to in the header of standalone HTML documents.
.RS
.RE
.TP
.B \-\-gladtex
Enclose TeX math in \f[C]<eq>\f[] tags in HTML output.
These can then be processed by gladTeX to produce links to images of the
typeset formulas.
.RS
.RE
.TP
.B \-\-mimetex=\f[I]URL\f[]
Render TeX math using the mimeTeX CGI script.
If \f[I]URL\f[] is not specified, it is assumed that the script is at
\f[C]/cgi\-bin/mimetex.cgi\f[].
.RS
.RE
.TP
.B \-\-webtex=\f[I]URL\f[]
Render TeX math using an external script.
The formula will be concatenated with the URL provided.
If \f[I]URL\f[] is not specified, the Google Chart API will be used.
.RS
.RE
.TP
.B \-i, \-\-incremental
Make list items in Slidy or S5 display incrementally (one by one).
.RS
.RE
.TP
.B \-\-offline
Include all the CSS and javascript needed for a Slidy or S5 slide show
in the output, so that the slide show will work even when no internet
connection is available.
.RS
.RE
.TP
.B \-\-xetex
Create LaTeX outut suitable for processing by XeTeX.
.RS
.RE
.TP
.B \-N, \-\-number\-sections
Number section headings in LaTeX, ConTeXt, or HTML output.
(Default is not to number them.)
.RS
.RE
.TP
.B \-\-section\-divs
Wrap sections in \f[C]<div>\f[] tags, and attach identifiers to the
enclosing \f[C]<div>\f[] rather than the header itself.
.RS
.RE
.TP
.B \-\-no\-wrap
Disable text wrapping in output.
(Default is to wrap text.)
.RS
.RE
.TP
.B \-\-sanitize\-html
Sanitizes HTML (in markdown or HTML input) using a whitelist.
Unsafe tags are replaced by HTML comments; unsafe attributes are
omitted.
URIs in links and images are also checked against a whitelist of URI
schemes.
.RS
.RE
.TP
.B \-\-email\-obfuscation=\f[I]none|javascript|references\f[]
Specify a method for obfuscating \f[C]mailto:\f[] links in HTML
documents.
\f[I]none\f[] leaves \f[C]mailto:\f[] links as they are.
\f[I]javascript\f[] obfuscates them using javascript.
\f[I]references\f[] obfuscates them by printing their letters as decimal
or hexadecimal character references.
If \f[C]\-\-strict\f[] is specified, \f[I]references\f[] is used
regardless of the presence of this option.
.RS
.RE
.TP
.B \-\-id\-prefix\f[I]=string\f[]
Specify a prefix to be added to all automatically generated identifiers
in HTML output.
This is useful for preventing duplicate identifiers when generating
fragments to be included in other pages.
.RS
.RE
.TP
.B \-\-indented\-code\-classes\f[I]=classes\f[]
Specify classes to use for indented code blocks\-\-for example,
\f[C]perl,numberLines\f[] or \f[C]haskell\f[].
Multiple classes may be separated by spaces or commas.
.RS
.RE
.TP
.B \-\-toc, \-\-table\-of\-contents
Include an automatically generated table of contents (HTML, markdown,
RTF) or an instruction to create one (LaTeX, reStructuredText).
This option has no effect on man, DocBook, Slidy, or S5 output.
.RS
.RE
.TP
.B \-\-base\-header\-level=\f[I]LEVEL\f[]
Specify the base level for headers (defaults to 1).
.RS
.RE
.TP
.B \-\-template=\f[I]FILE\f[]
Use \f[I]FILE\f[] as a custom template for the generated document.
Implies \f[C]\-s\f[].
See TEMPLATES below for a description of template syntax.
If this option is not used, a default template appropriate for the
output format will be used.
See also \f[C]\-D/\-\-print\-default\-template\f[].
.RS
.RE
.TP
.B \-V KEY=VAL, \-\-variable=\f[I]KEY:VAL\f[]
Set the template variable KEY to the value VAL when rendering the
document in standalone mode.
This is only useful when the \f[C]\-\-template\f[] option is used to
specify a custom template, since pandoc automatically sets the variables
used in the default templates.
.RS
.RE
.TP
.B \-c \f[I]CSS\f[], \-\-css=\f[I]CSS\f[]
Link to a CSS style sheet.
\f[I]CSS\f[] is the pathname of the style sheet.
.RS
.RE
.TP
.B \-H \f[I]FILE\f[], \-\-include\-in\-header=\f[I]FILE\f[]
Include contents of \f[I]FILE\f[] at the end of the header.
Implies \f[C]\-s\f[].
.RS
.RE
.TP
.B \-B \f[I]FILE\f[], \-\-include\-before\-body=\f[I]FILE\f[]
Include contents of \f[I]FILE\f[] at the beginning of the document body.
Implies \f[C]\-s\f[].
.RS
.RE
.TP
.B \-A \f[I]FILE\f[], \-\-include\-after\-body=\f[I]FILE\f[]
Include contents of \f[I]FILE\f[] at the end of the document body.
Implies \f[C]\-s\f[].
.RS
.RE
.TP
.B \-C \f[I]FILE\f[], \-\-custom\-header=\f[I]FILE\f[]
Use contents of \f[I]FILE\f[] as the document header.
\f[I]Note: This option is deprecated. Users should transition to using
\f[C]\-\-template\f[] instead.\f[]
.RS
.RE
.TP
.B \-\-reference\-odt=\f[I]filename\f[]
Use the specified file as a style reference in producing an ODT.
For best results, the reference ODT should be a modified version of an
ODT produced using pandoc.
The contents of the reference ODT are ignored, but its stylesheets are
used in the new ODT.
If no reference ODT is specified on the command line, pandoc will look
for a file \f[C]reference.odt\f[] in the user data directory (see
\f[C]\-\-data\-dir\f[]).
If this is not found either, sensible defaults will be used.
.RS
.RE
.TP
.B \-\-epub\-stylesheet=\f[I]filename\f[]
Use the specified CSS file to style the EPUB.
If no stylesheet is specified, pandoc will look for a file
\f[C]epub.css\f[] in the user data directory (see
\f[C]\-\-data\-dir\f[], below).
If it is not found there, sensible defaults will be used.
.RS
.RE
.TP
.B \-\-epub\-metadata=\f[I]filename\f[]
Look in the specified XML file for metadata for the EPUB.
The file should contain a series of Dublin Core elements
(http://dublincore.org/documents/dces/), for example:
.RS
.IP
.nf
\f[C]
\ <dc:rights>Creative\ Commons</dc:rights>
\ <dc:language>es\-AR</dc:language>
\f[]
.fi
.PP
By default, pandoc will include the following metadata elements:
\f[C]<dc:title>\f[] (from the document title), \f[C]<dc:creator>\f[]
(from the document authors), \f[C]<dc:language>\f[] (from the locale),
and \f[C]<dc:identifier\ id="BookId">\f[] (a randomly generated UUID).
Any of these may be overridden by elements in the metadata file.
.RE
.TP
.B \-D \f[I]FORMAT\f[], \-\-print\-default\-template=\f[I]FORMAT\f[]
Print the default template for an output \f[I]FORMAT\f[].
(See \f[C]\-t\f[] for a list of possible \f[I]FORMAT\f[]s.)
.RS
.RE
.TP
.B \-T \f[I]STRING\f[], \-\-title\-prefix=\f[I]STRING\f[]
Specify \f[I]STRING\f[] as a prefix to the HTML window title.
.RS
.RE
.TP
.B \-\-data\-dir\f[I]=DIRECTORY\f[]
Specify the user data directory to search for pandoc data files.
If this option is not specified, the default user data directory will be
used:
.RS
.IP
.nf
\f[C]
$HOME/.pandoc
\f[]
.fi
.PP
in unix and
.IP
.nf
\f[C]
C:\\Documents\ And\ Settings\\USERNAME\\Application\ Data\\pandoc
\f[]
.fi
.PP
in Windows.
A \f[C]reference.odt\f[], \f[C]epub.css\f[], \f[C]templates\f[]
directory, or \f[C]s5\f[] directory placed in this directory will
override pandoc\[aq]s normal defaults.
.RE
.TP
.B \-\-dump\-args
Print information about command\-line arguments to \f[I]stdout\f[], then
exit.
The first line of output contains the name of the output file specified
with the \f[C]\-o\f[] option, or `\f[C]\-\f[]\[aq] (for \f[I]stdout\f[])
if no output file was specified.
The remaining lines contain the command\-line arguments, one per line,
in the order they appear.
These do not include regular Pandoc options and their arguments, but do
include any options appearing after a `\f[C]\-\-\f[]\[aq] separator at
the end of the line.
This option is intended primarily for use in wrapper scripts.
.RS
.RE
.TP
.B \-\-ignore\-args
Ignore command\-line arguments (for use in wrapper scripts).
Regular Pandoc options are not ignored.
Thus, for example,
.RS
.IP
.nf
\f[C]
pandoc\ \-\-ignore\-args\ \-o\ foo.html\ \-s\ foo.txt\ \-\-\ \-e\ latin1
\f[]
.fi
.PP
is equivalent to
.IP
.nf
\f[C]
pandoc\ \-o\ foo.html\ \-s
\f[]
.fi
.RE
.TP
.B \-v, \-\-version
Print version.
.RS
.RE
.TP
.B \-h, \-\-help
Show usage message.
.RS
.RE
.SH TEMPLATES
.PP
When the \f[C]\-s/\-\-standalone\f[] option is used, pandoc uses a
template to add header and footer material that is needed for a
self\-standing document.
To see the default template that is used, just type
.IP
.nf
\f[C]
pandoc\ \-\-print\-default\-template=FORMAT
\f[]
.fi
.PP
where \f[C]FORMAT\f[] is the name of the output format.
A custom template can be specified using the \f[C]\-\-template\f[]
option.
You can also override the system default templates for a given output
format \f[C]FORMAT\f[] by putting a file
\f[C]templates/FORMAT.template\f[] in the user data directory (see
\f[C]\-\-data\-dir\f[], below).
.PP
Templates may contain \f[I]variables\f[].
Variable names are sequences of alphanumerics, \f[C]\-\f[], and
\f[C]_\f[], starting with a letter.
A variable name surrounded by \f[C]$\f[] signs will be replaced by its
value.
For example, the string \f[C]$title$\f[] in
.IP
.nf
\f[C]
<title>$title$</title>
\f[]
.fi
.PP
will be replaced by the document title.
.PP
To write a literal \f[C]$\f[] in a template, use \f[C]$$\f[].
.PP
Some variables are set automatically by pandoc.
These vary somewhat depending on the output format, but include:
.TP
.B \f[C]legacy\-header\f[]
contents specified by \f[C]\-C/\-\-custom\-header\f[]
.RS
.RE
.TP
.B \f[C]header\-includes\f[]
contents specified by \f[C]\-H/\-\-include\-in\-header\f[] (may have
multiple values)
.RS
.RE
.TP
.B \f[C]toc\f[]
non\-null value if \f[C]\-\-toc/\-\-table\-of\-contents\f[] was
specified
.RS
.RE
.TP
.B \f[C]include\-before\f[]
contents specified by \f[C]\-B/\-\-include\-before\-body\f[] (may have
multiple values)
.RS
.RE
.TP
.B \f[C]include\-after\f[]
contents specified by \f[C]\-A/\-\-include\-after\-body\f[] (may have
multiple values)
.RS
.RE
.TP
.B \f[C]body\f[]
body of document
.RS
.RE
.TP
.B \f[C]title\f[]
title of document, as specified in title block
.RS
.RE
.TP
.B \f[C]author\f[]
author of document, as specified in title block (may have multiple
values)
.RS
.RE
.TP
.B \f[C]date\f[]
date of document, as specified in title block
.RS
.RE
.PP
Variables may be set at the command line using the
\f[C]\-V/\-\-variable\f[] option.
This allows users to include custom variables in their templates.
.PP
Templates may contain conditionals.
The syntax is as follows:
.IP
.nf
\f[C]
$if(variable)$
X\ 
$else$
Y
$endif$
\f[]
.fi
.PP
This will include \f[C]X\f[] in the template if \f[C]variable\f[] has a
non\-null value; otherwise it will include \f[C]Y\f[].
\f[C]X\f[] and \f[C]Y\f[] are placeholders for any valid template text,
and may include interpolated variables or other conditionals.
The \f[C]$else$\f[] section may be omitted.
.PP
When variables can have multiple values (for example, \f[C]author\f[] in
a multi\-author document), you can use the \f[C]$for$\f[] keyword:
.IP
.nf
\f[C]
$for(author)$
<meta\ name="author"\ content="$author$"\ />
$endfor$
\f[]
.fi
.PP
You can optionally specify a separator to be used between consecutive
items:
.IP
.nf
\f[C]
$for(author)$$author$$sep$,\ $endfor$
\f[]
.fi
.SH SEE ALSO
.PP
\f[C]markdown2pdf\f[] (1).
The \f[I]README\f[] file distributed with Pandoc contains full
documentation.
.PP
The Pandoc source code and all documentation may be downloaded from
<http://johnmacfarlane.net/pandoc/>.
.SH AUTHORS
John MacFarlane.
